# Generated by Django 4.2.23 on 2025-07-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('pasillo', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=100)),
                ('cod_ean', models.CharField(max_length=50)),
                ('cod_dun', models.CharField(max_length=50)),
                ('cod_sistema', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('unidad', models.CharField(max_length=50)),
                ('pack', models.CharField(max_length=50)),
                ('factorx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cajas', models.PositiveIntegerField()),
                ('saldo', models.PositiveIntegerField()),
                ('stock_fisico', models.PositiveIntegerField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_venc', models.DateField()),
                ('fecha_imp', models.DateField()),
                ('contenedor', models.CharField(max_length=100)),
                ('fecha_inv', models.DateField()),
                ('encargado', models.CharField(max_length=100)),
            ],
        ),
    ]
